/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    users: UserAuthOperations;
  };
  collections: {
    admins: Admin;
    courses: Course;
    document: Document;
    events: Event;
    guidelines: Guideline;
    links: Link;
    topics: Topic;
    media: Media;
    news: News;
    publications: Publication;
    users: User;
    videos: Video;
    'video-files': VideoFile;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    document: DocumentSelect<false> | DocumentSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    guidelines: GuidelinesSelect<false> | GuidelinesSelect<true>;
    links: LinksSelect<false> | LinksSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    'video-files': VideoFilesSelect<false> | VideoFilesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user:
    | (Admin & {
        collection: 'admins';
      })
    | (User & {
        collection: 'users';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: string;
  title: string;
  content_type: 'file' | 'url';
  document?: (string | null) | Document;
  url?: string | null;
  topics?: (string | Topic)[] | null;
  featured_image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document".
 */
export interface Document {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: string;
  title: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  event_type: '1st_party' | 'sponsored' | 'other';
  start_date: string;
  end_date?: string | null;
  Links?: {
    official_page_url?: string | null;
    signup_url?: string | null;
    programme_url?: string | null;
  };
  sections?: TextBlock[] | null;
  is_featured?: boolean | null;
  topics?: (string | Topic)[] | null;
  featured_image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  quoteHeader: string;
  quoteText?: string | null;
  djfsoks?: (string | Media)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guidelines".
 */
export interface Guideline {
  id: string;
  title: string;
  content_type: 'file' | 'url';
  document?: (string | null) | Document;
  url?: string | null;
  topics?: (string | Topic)[] | null;
  featured_image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links".
 */
export interface Link {
  id: string;
  title: string;
  subtitle?: string | null;
  href: string;
  sort_order: number;
  is_active?: boolean | null;
  is_featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  title: string;
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  is_featured?: boolean | null;
  topics?: (string | Topic)[] | null;
  featured_image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: string;
  title: string;
  content_type: 'file' | 'url';
  document?: (string | null) | Document;
  url?: string | null;
  topics?: (string | Topic)[] | null;
  featured_image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  title?: ('Sr.' | 'Sr.ª' | 'Dr.' | 'Dr.ª' | 'Prof.' | 'Prof.ª' | 'Exmo.' | 'Exmo.ª') | null;
  first_name?: string | null;
  last_name?: string | null;
  tax_id?: number | null;
  medical_id?: number | null;
  birthday?: string | null;
  phone?: string | null;
  email: string;
  address_1?: string | null;
  address_2?: string | null;
  postal_code?: string | null;
  city?: string | null;
  country?: string | null;
  workplace_primary?: string | null;
  workplace_secondary?: string | null;
  subscribed_sections?:
    | (
        | 'colposcopia_patologia_tracto_genital_inferior'
        | 'endoscopia_ginecologica'
        | 'ginecologia_oncologica'
        | 'menopausa'
        | 'uroginecologia'
      )[]
    | null;
  billing_name?: string | null;
  billing_tax_id?: number | null;
  billing_address_1?: string | null;
  billing_address_2?: string | null;
  billing_postal_code?: string | null;
  billing_city?: string | null;
  stripe_id?: string | null;
  invoices?:
    | {
        invoice_number?: string | null;
        invoice_date?: string | null;
        invoice_id?: string | null;
        invoice_system_time?: string | null;
        id?: string | null;
      }[]
    | null;
  account_status?: ('active' | 'pending') | null;
  updatedAt: string;
  createdAt: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: string;
  title?: string | null;
  status?: ('draft' | 'in_review' | 'approved' | 'rejected') | null;
  video_file?: (string | null) | VideoFile;
  declaration_file?: (string | null) | Media;
  authors?: string | null;
  section?:
    | (
        | 'geral'
        | 'colposcopia_patologia_tracto_genital_inferior'
        | 'endoscopia_ginecologica'
        | 'ginecologia_oncologica'
        | 'menopausa'
        | 'uroginecologia'
      )
    | null;
  introduction?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publisher?: (string | null) | User;
  views?: number | null;
  is_featured?: boolean | null;
  topics?: (string | Topic)[] | null;
  featured_image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-files".
 */
export interface VideoFile {
  id: string;
  duration?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'admins';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'courses';
        value: string | Course;
      } | null)
    | ({
        relationTo: 'document';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'guidelines';
        value: string | Guideline;
      } | null)
    | ({
        relationTo: 'links';
        value: string | Link;
      } | null)
    | ({
        relationTo: 'topics';
        value: string | Topic;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'publications';
        value: string | Publication;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'videos';
        value: string | Video;
      } | null)
    | ({
        relationTo: 'video-files';
        value: string | VideoFile;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: string | Admin;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'admins';
        value: string | Admin;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  content_type?: T;
  document?: T;
  url?: T;
  topics?: T;
  featured_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document_select".
 */
export interface DocumentSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  event_type?: T;
  start_date?: T;
  end_date?: T;
  Links?:
    | T
    | {
        official_page_url?: T;
        signup_url?: T;
        programme_url?: T;
      };
  sections?:
    | T
    | {
        Text?: T | TextBlockSelect<T>;
      };
  is_featured?: T;
  topics?: T;
  featured_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  quoteHeader?: T;
  quoteText?: T;
  djfsoks?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guidelines_select".
 */
export interface GuidelinesSelect<T extends boolean = true> {
  title?: T;
  content_type?: T;
  document?: T;
  url?: T;
  topics?: T;
  featured_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_select".
 */
export interface LinksSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  href?: T;
  sort_order?: T;
  is_active?: T;
  is_featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  body?: T;
  is_featured?: T;
  topics?: T;
  featured_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  content_type?: T;
  document?: T;
  url?: T;
  topics?: T;
  featured_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  title?: T;
  first_name?: T;
  last_name?: T;
  tax_id?: T;
  medical_id?: T;
  birthday?: T;
  phone?: T;
  email?: T;
  address_1?: T;
  address_2?: T;
  postal_code?: T;
  city?: T;
  country?: T;
  workplace_primary?: T;
  workplace_secondary?: T;
  subscribed_sections?: T;
  billing_name?: T;
  billing_tax_id?: T;
  billing_address_1?: T;
  billing_address_2?: T;
  billing_postal_code?: T;
  billing_city?: T;
  stripe_id?: T;
  invoices?:
    | T
    | {
        invoice_number?: T;
        invoice_date?: T;
        invoice_id?: T;
        invoice_system_time?: T;
        id?: T;
      };
  account_status?: T;
  updatedAt?: T;
  createdAt?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  video_file?: T;
  declaration_file?: T;
  authors?: T;
  section?: T;
  introduction?: T;
  description?: T;
  publisher?: T;
  views?: T;
  is_featured?: T;
  topics?: T;
  featured_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-files_select".
 */
export interface VideoFilesSelect<T extends boolean = true> {
  duration?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}