/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    courses: Course;
    documents: Document;
    events: Event;
    guidelines: Guideline;
    'internal-documents': InternalDocument;
    links: Link;
    topics: Topic;
    media: Media;
    news: News;
    quotas: Quota;
    publications: Publication;
    sections: Section;
    users: User;
    videos: Video;
    'video-files': VideoFile;
    workgroups: Workgroup;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    guidelines: GuidelinesSelect<false> | GuidelinesSelect<true>;
    'internal-documents': InternalDocumentsSelect<false> | InternalDocumentsSelect<true>;
    links: LinksSelect<false> | LinksSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    quotas: QuotasSelect<false> | QuotasSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    'video-files': VideoFilesSelect<false> | VideoFilesSelect<true>;
    workgroups: WorkgroupsSelect<false> | WorkgroupsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'legal-documents': LegalDocument;
    'social-bodies': SocialBody;
  };
  globalsSelect: {
    'legal-documents': LegalDocumentsSelect<false> | LegalDocumentsSelect<true>;
    'social-bodies': SocialBodiesSelect<false> | SocialBodiesSelect<true>;
  };
  locale: null;
  user:
    | (Admin & {
        collection: 'admins';
      })
    | (User & {
        collection: 'users';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: string;
  title: string;
  content_type: 'file' | 'url';
  document?: (string | null) | Document;
  url?: string | null;
  topics?: (string | Topic)[] | null;
  featured_image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: string;
  title: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  event_type: '1st_party' | 'sponsored' | 'other';
  start_date: string;
  end_date?: string | null;
  Links?: {
    official_page_url?: string | null;
    signup_url?: string | null;
    programme_url?: string | null;
  };
  sections?: TextBlock[] | null;
  is_featured?: boolean | null;
  topics?: (string | Topic)[] | null;
  featured_image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  quoteHeader: string;
  quoteText?: string | null;
  djfsoks?: (string | Media)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guidelines".
 */
export interface Guideline {
  id: string;
  title: string;
  content_type: 'file' | 'url';
  document?: (string | null) | Document;
  url?: string | null;
  topics?: (string | Topic)[] | null;
  publishedAt: string;
  featured_image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal-documents".
 */
export interface InternalDocument {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links".
 */
export interface Link {
  id: string;
  title: string;
  subtitle?: string | null;
  href: string;
  sort_order: number;
  is_active?: boolean | null;
  is_featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  title: string;
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  is_featured?: boolean | null;
  topics?: (string | Topic)[] | null;
  featured_image?: (string | null) | Media;
  publishedAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotas".
 */
export interface Quota {
  id: string;
  year: number;
  amount: number;
  is_enabled: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: string;
  title: string;
  content_type: 'file' | 'url';
  document?: (string | null) | Document;
  url?: string | null;
  topics?: (string | Topic)[] | null;
  featured_image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: string;
  title: string;
  intro_text: string;
  project_description: string;
  goal_description: string;
  social_bodies?:
    | {
        name: string;
        position?: string | null;
        city?: string | null;
        photo?: (string | null) | Media;
        separated_from_next?: boolean | null;
        id?: string | null;
      }[]
    | null;
  useful_links?:
    | {
        title: string;
        content_type: 'file' | 'url';
        document?: (string | null) | Document;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  slug: string;
  topics?: (string | Topic)[] | null;
  featured_image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  title?: ('' | 'Sr.' | 'Sr.ª' | 'Dr.' | 'Dr.ª' | 'Prof.' | 'Prof.ª' | 'Exmo.' | 'Exmo.ª') | null;
  first_name?: string | null;
  last_name?: string | null;
  tax_id: string;
  medical_id?: number | null;
  birthday?: string | null;
  member_since: number;
  send_newsletter?: boolean | null;
  phone?: string | null;
  address_1?: string | null;
  address_2?: string | null;
  postal_code?: string | null;
  city?: string | null;
  country?: string | null;
  workplace_primary?: string | null;
  workplace_secondary?: string | null;
  subscribed_sections?:
    | (
        | 'colposcopia_patologia_tracto_genital_inferior'
        | 'endoscopia_ginecologica'
        | 'ginecologia_oncologica'
        | 'menopausa'
        | 'uroginecologia'
      )[]
    | null;
  billing_name?: string | null;
  billing_tax_id?: string | null;
  billing_address_1?: string | null;
  billing_address_2?: string | null;
  billing_postal_code?: string | null;
  billing_city?: string | null;
  quotas?:
    | {
        request_date: string;
        year: number;
        payment_amount: number;
        payment_status: 'waiting' | 'paid' | 'refunded' | 'canceled';
        payment_link_id: string;
        payment_link_url: string;
        invoices?:
          | {
              doc_id: string;
              doc_number: string;
              doc_system_time: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  account_status?: ('active' | 'waiting' | 'dormant') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: string;
  title?: string | null;
  status: 'draft' | 'in_review' | 'approved' | 'rejected';
  video_file?: (string | null) | VideoFile;
  declaration_file?: (string | null) | InternalDocument;
  authors?: string | null;
  section?:
    | (
        | 'geral'
        | 'colposcopia_patologia_tracto_genital_inferior'
        | 'endoscopia_ginecologica'
        | 'ginecologia_oncologica'
        | 'menopausa'
        | 'uroginecologia'
      )
    | null;
  introduction?: string | null;
  description?: string | null;
  publisher?: (string | null) | User;
  views?: number | null;
  is_featured?: boolean | null;
  topics?: (string | Topic)[] | null;
  publishedAt: string;
  featured_image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-files".
 */
export interface VideoFile {
  id: string;
  duration?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workgroups".
 */
export interface Workgroup {
  id: string;
  title: string;
  intro_text: string;
  project_description: string;
  goal_description: string;
  social_bodies?:
    | {
        name: string;
        position?: string | null;
        city?: string | null;
        photo?: (string | null) | Media;
        separated_from_next?: boolean | null;
        id?: string | null;
      }[]
    | null;
  useful_links?:
    | {
        title: string;
        content_type: 'file' | 'url';
        document?: (string | null) | Document;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  slug: string;
  topics?: (string | Topic)[] | null;
  featured_image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'admins';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'courses';
        value: string | Course;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'guidelines';
        value: string | Guideline;
      } | null)
    | ({
        relationTo: 'internal-documents';
        value: string | InternalDocument;
      } | null)
    | ({
        relationTo: 'links';
        value: string | Link;
      } | null)
    | ({
        relationTo: 'topics';
        value: string | Topic;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'quotas';
        value: string | Quota;
      } | null)
    | ({
        relationTo: 'publications';
        value: string | Publication;
      } | null)
    | ({
        relationTo: 'sections';
        value: string | Section;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'videos';
        value: string | Video;
      } | null)
    | ({
        relationTo: 'video-files';
        value: string | VideoFile;
      } | null)
    | ({
        relationTo: 'workgroups';
        value: string | Workgroup;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: string | Admin;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'admins';
        value: string | Admin;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  content_type?: T;
  document?: T;
  url?: T;
  topics?: T;
  featured_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  event_type?: T;
  start_date?: T;
  end_date?: T;
  Links?:
    | T
    | {
        official_page_url?: T;
        signup_url?: T;
        programme_url?: T;
      };
  sections?:
    | T
    | {
        Text?: T | TextBlockSelect<T>;
      };
  is_featured?: T;
  topics?: T;
  featured_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  quoteHeader?: T;
  quoteText?: T;
  djfsoks?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guidelines_select".
 */
export interface GuidelinesSelect<T extends boolean = true> {
  title?: T;
  content_type?: T;
  document?: T;
  url?: T;
  topics?: T;
  publishedAt?: T;
  featured_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal-documents_select".
 */
export interface InternalDocumentsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_select".
 */
export interface LinksSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  href?: T;
  sort_order?: T;
  is_active?: T;
  is_featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  body?: T;
  is_featured?: T;
  topics?: T;
  featured_image?: T;
  publishedAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotas_select".
 */
export interface QuotasSelect<T extends boolean = true> {
  year?: T;
  amount?: T;
  is_enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  content_type?: T;
  document?: T;
  url?: T;
  topics?: T;
  featured_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  title?: T;
  intro_text?: T;
  project_description?: T;
  goal_description?: T;
  social_bodies?:
    | T
    | {
        name?: T;
        position?: T;
        city?: T;
        photo?: T;
        separated_from_next?: T;
        id?: T;
      };
  useful_links?:
    | T
    | {
        title?: T;
        content_type?: T;
        document?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  topics?: T;
  featured_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  title?: T;
  first_name?: T;
  last_name?: T;
  tax_id?: T;
  medical_id?: T;
  birthday?: T;
  member_since?: T;
  send_newsletter?: T;
  phone?: T;
  address_1?: T;
  address_2?: T;
  postal_code?: T;
  city?: T;
  country?: T;
  workplace_primary?: T;
  workplace_secondary?: T;
  subscribed_sections?: T;
  billing_name?: T;
  billing_tax_id?: T;
  billing_address_1?: T;
  billing_address_2?: T;
  billing_postal_code?: T;
  billing_city?: T;
  quotas?:
    | T
    | {
        request_date?: T;
        year?: T;
        payment_amount?: T;
        payment_status?: T;
        payment_link_id?: T;
        payment_link_url?: T;
        invoices?:
          | T
          | {
              doc_id?: T;
              doc_number?: T;
              doc_system_time?: T;
              id?: T;
            };
        id?: T;
      };
  account_status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  video_file?: T;
  declaration_file?: T;
  authors?: T;
  section?: T;
  introduction?: T;
  description?: T;
  publisher?: T;
  views?: T;
  is_featured?: T;
  topics?: T;
  publishedAt?: T;
  featured_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-files_select".
 */
export interface VideoFilesSelect<T extends boolean = true> {
  duration?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workgroups_select".
 */
export interface WorkgroupsSelect<T extends boolean = true> {
  title?: T;
  intro_text?: T;
  project_description?: T;
  goal_description?: T;
  social_bodies?:
    | T
    | {
        name?: T;
        position?: T;
        city?: T;
        photo?: T;
        separated_from_next?: T;
        id?: T;
      };
  useful_links?:
    | T
    | {
        title?: T;
        content_type?: T;
        document?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  topics?: T;
  featured_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents".
 */
export interface LegalDocument {
  id: string;
  docs?:
    | {
        title: string;
        content_type: 'file' | 'url';
        document?: (string | null) | Document;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-bodies".
 */
export interface SocialBody {
  id: string;
  direction?:
    | {
        name: string;
        position?: string | null;
        city?: string | null;
        photo?: (string | null) | Media;
        separated_from_next?: boolean | null;
        id?: string | null;
      }[]
    | null;
  general_assembly?:
    | {
        name: string;
        position?: string | null;
        city?: string | null;
        photo?: (string | null) | Media;
        separated_from_next?: boolean | null;
        id?: string | null;
      }[]
    | null;
  fiscal_council?:
    | {
        name: string;
        position?: string | null;
        city?: string | null;
        photo?: (string | null) | Media;
        separated_from_next?: boolean | null;
        id?: string | null;
      }[]
    | null;
  consultive_council?:
    | {
        name: string;
        position?: string | null;
        city?: string | null;
        photo?: (string | null) | Media;
        separated_from_next?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents_select".
 */
export interface LegalDocumentsSelect<T extends boolean = true> {
  docs?:
    | T
    | {
        title?: T;
        content_type?: T;
        document?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-bodies_select".
 */
export interface SocialBodiesSelect<T extends boolean = true> {
  direction?:
    | T
    | {
        name?: T;
        position?: T;
        city?: T;
        photo?: T;
        separated_from_next?: T;
        id?: T;
      };
  general_assembly?:
    | T
    | {
        name?: T;
        position?: T;
        city?: T;
        photo?: T;
        separated_from_next?: T;
        id?: T;
      };
  fiscal_council?:
    | T
    | {
        name?: T;
        position?: T;
        city?: T;
        photo?: T;
        separated_from_next?: T;
        id?: T;
      };
  consultive_council?:
    | T
    | {
        name?: T;
        position?: T;
        city?: T;
        photo?: T;
        separated_from_next?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}