volumes:
  certbotdata:
  spgdbdata:

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=10
      - WATCHTOWER_CLEANUP=TRUE
      - WATCHTOWER_INCLUDE_STOPPED=TRUE
      - WATCHTOWER_REVIVE_STOPPED=TRUE
      - WATCHTOWER_ROLLING_RESTART=TRUE

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  nginx:
    image: ghcr.io/spginecologia/website-nginx:production
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          memory: 1gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./letsencrypt:/etc/letsencrypt:ro
      - certbotdata:/var/www/certbot:ro
    ports:
      - 80:80
      - 443:443

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  spgdb:
    image: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - spgdbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=spgdbuser
      - MONGO_INITDB_ROOT_PASSWORD=spgdbpassword

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  backupd:
    image: ghcr.io/spginecologia/website-backupd:production
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./backups/:/backups
    env_file:
      - .env.production

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  frontend:
    image: ghcr.io/spginecologia/website-frontend:production
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    environment:
      - VERCEL_URL=dev.spginecologia.pt
    env_file:
      - .env.production
