/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    paginas: Pagina;
    events: Event;
    users: User;
    media: Media;
    categories: Category;
    consensos: Consenso;
    noticias: Noticia;
    publications: Publication;
    courses: Course;
    sections: Section;
    nucleos: Nucleo;
    members: Member;
    videos: Video;
    prizes: Prize;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    paginas: PaginasSelect<false> | PaginasSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    consensos: ConsensosSelect<false> | ConsensosSelect<true>;
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    nucleos: NucleosSelect<false> | NucleosSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    prizes: PrizesSelect<false> | PrizesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
    newVideoPage: NewVideoPage;
    account: Account;
    videosPage: VideosPage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    newVideoPage: NewVideoPageSelect<false> | NewVideoPageSelect<true>;
    account: AccountSelect<false> | AccountSelect<true>;
    videosPage: VideosPageSelect<false> | VideosPageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: string;
  titulo?: string | null;
  slug?: string | null;
  layout?: unknown[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  is_featured?: boolean | null;
  event_type: 'spg' | 'patrocinado' | 'outros';
  start_date: string;
  end_date: string;
  links_group?: {
    link_to_official_page?: string | null;
    link_to_facebook?: string | null;
    link_to_register?: string | null;
    link_to_program?: string | null;
  };
  sections?:
    | {
        title?: string | null;
        evento_section_type?: ('text' | 'images' | 'video' | 'iframe') | null;
        content?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        video?: string | null;
        iframe?: string | null;
        images?:
          | {
              image: string | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  description?: string | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  title?: ('Sr.' | 'Sr.ª' | 'Dr.' | 'Dr.ª' | 'Prof.' | 'Prof.ª' | 'Exmo.' | 'Exmo.ª') | null;
  name?: string | null;
  last_name?: string | null;
  full_name?: string | null;
  cellphone?: number | null;
  partner_number?: number | null;
  tax_number?: number | null;
  date?: string | null;
  prime_workplace?: string | null;
  secondary_workplace?: string | null;
  colposcopia_patologia_tracto_genital_inferior?: boolean | null;
  endoscopia_genecologica?: boolean | null;
  ginecologia_oncologica?: boolean | null;
  menopausa?: boolean | null;
  uroginecologia?: boolean | null;
  address?: string | null;
  address_cont?: string | null;
  post_code?: string | null;
  city?: string | null;
  country?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consensos".
 */
export interface Consenso {
  id: string;
  title: string;
  consenso_type: 'file' | 'url';
  consenso_file?: (string | null) | Media;
  consenso_url?: string | null;
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: string;
  title: string;
  is_featured?: boolean | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: string;
  title: string;
  publication_file: string | Media;
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: string;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: string;
  title: string;
  mission: string;
  first_column: {
    title: string;
    message: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  second_column: {
    title: string;
    message: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  members?:
    | {
        picture?: (string | null) | Media;
        name: string;
        position?: string | null;
        location?: string | null;
        id?: string | null;
      }[]
    | null;
  useful_links?:
    | {
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  buttons?:
    | {
        title: string;
        type?: ('url' | 'file') | null;
        url?: string | null;
        file?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  recomended_articles?:
    | {
        title: string;
        type?: ('url' | 'file') | null;
        url?: string | null;
        file?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  workshops?:
    | {
        title: string;
        type?: ('url' | 'file') | null;
        url?: string | null;
        file?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  contacts?:
    | {
        type?: ('email' | 'phone') | null;
        email?: string | null;
        phone?: string | null;
        id?: string | null;
      }[]
    | null;
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nucleos".
 */
export interface Nucleo {
  id: string;
  title: string;
  mission: string;
  first_column: {
    title: string;
    message: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  second_column: {
    title: string;
    message: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  members?:
    | {
        picture?: (string | null) | Media;
        name: string;
        position?: string | null;
        location?: string | null;
        id?: string | null;
      }[]
    | null;
  useful_links?:
    | {
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  buttons?:
    | {
        title: string;
        type?: ('url' | 'file') | null;
        url?: string | null;
        file?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  recomended_articles?:
    | {
        title: string;
        type?: ('url' | 'file') | null;
        url?: string | null;
        file?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  workshops?:
    | {
        title: string;
        type?: ('url' | 'file') | null;
        url?: string | null;
        file?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  contacts?:
    | {
        type?: ('email' | 'phone') | null;
        email?: string | null;
        phone?: string | null;
        id?: string | null;
      }[]
    | null;
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: string;
  name: string;
  profile_picture: string | Media;
  position?: string | null;
  location?: string | null;
  social_body?: ('direcao' | 'assembleia-geral' | 'conselho-fiscal' | 'conselho-consultivo') | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: string;
  title: string;
  video_featured?: boolean | null;
  video_rgpd_confirmation: boolean;
  video_file_length?: string | null;
  video_file: string | Media;
  video_declaration_signed?: (string | null) | Media;
  video_authors: string;
  video_section:
    | 'geral'
    | 'colposcopia_patologia_tracto_genital_inferior'
    | 'endoscopia_ginecologica'
    | 'ginecologia_oncologica'
    | 'menopausa'
    | 'uroginecologia';
  video_introduction: string;
  video_description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author: string | User;
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prizes".
 */
export interface Prize {
  id: string;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'paginas';
        value: string | Pagina;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'consensos';
        value: string | Consenso;
      } | null)
    | ({
        relationTo: 'noticias';
        value: string | Noticia;
      } | null)
    | ({
        relationTo: 'publications';
        value: string | Publication;
      } | null)
    | ({
        relationTo: 'courses';
        value: string | Course;
      } | null)
    | ({
        relationTo: 'sections';
        value: string | Section;
      } | null)
    | ({
        relationTo: 'nucleos';
        value: string | Nucleo;
      } | null)
    | ({
        relationTo: 'members';
        value: string | Member;
      } | null)
    | ({
        relationTo: 'videos';
        value: string | Video;
      } | null)
    | ({
        relationTo: 'prizes';
        value: string | Prize;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas_select".
 */
export interface PaginasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  layout?: T | {};
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  is_featured?: T;
  event_type?: T;
  start_date?: T;
  end_date?: T;
  links_group?:
    | T
    | {
        link_to_official_page?: T;
        link_to_facebook?: T;
        link_to_register?: T;
        link_to_program?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        evento_section_type?: T;
        content?: T;
        video?: T;
        iframe?: T;
        images?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
        id?: T;
      };
  slug?: T;
  categories?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  title?: T;
  name?: T;
  last_name?: T;
  full_name?: T;
  cellphone?: T;
  partner_number?: T;
  tax_number?: T;
  date?: T;
  prime_workplace?: T;
  secondary_workplace?: T;
  colposcopia_patologia_tracto_genital_inferior?: T;
  endoscopia_genecologica?: T;
  ginecologia_oncologica?: T;
  menopausa?: T;
  uroginecologia?: T;
  address?: T;
  address_cont?: T;
  post_code?: T;
  city?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consensos_select".
 */
export interface ConsensosSelect<T extends boolean = true> {
  title?: T;
  consenso_type?: T;
  consenso_file?: T;
  consenso_url?: T;
  slug?: T;
  categories?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  title?: T;
  is_featured?: T;
  content?: T;
  slug?: T;
  categories?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  publication_file?: T;
  slug?: T;
  categories?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  categories?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  title?: T;
  mission?: T;
  first_column?:
    | T
    | {
        title?: T;
        message?: T;
      };
  second_column?:
    | T
    | {
        title?: T;
        message?: T;
      };
  members?:
    | T
    | {
        picture?: T;
        name?: T;
        position?: T;
        location?: T;
        id?: T;
      };
  useful_links?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  buttons?:
    | T
    | {
        title?: T;
        type?: T;
        url?: T;
        file?: T;
        id?: T;
      };
  recomended_articles?:
    | T
    | {
        title?: T;
        type?: T;
        url?: T;
        file?: T;
        id?: T;
      };
  workshops?:
    | T
    | {
        title?: T;
        type?: T;
        url?: T;
        file?: T;
        id?: T;
      };
  contacts?:
    | T
    | {
        type?: T;
        email?: T;
        phone?: T;
        id?: T;
      };
  slug?: T;
  categories?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nucleos_select".
 */
export interface NucleosSelect<T extends boolean = true> {
  title?: T;
  mission?: T;
  first_column?:
    | T
    | {
        title?: T;
        message?: T;
      };
  second_column?:
    | T
    | {
        title?: T;
        message?: T;
      };
  members?:
    | T
    | {
        picture?: T;
        name?: T;
        position?: T;
        location?: T;
        id?: T;
      };
  useful_links?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  buttons?:
    | T
    | {
        title?: T;
        type?: T;
        url?: T;
        file?: T;
        id?: T;
      };
  recomended_articles?:
    | T
    | {
        title?: T;
        type?: T;
        url?: T;
        file?: T;
        id?: T;
      };
  workshops?:
    | T
    | {
        title?: T;
        type?: T;
        url?: T;
        file?: T;
        id?: T;
      };
  contacts?:
    | T
    | {
        type?: T;
        email?: T;
        phone?: T;
        id?: T;
      };
  slug?: T;
  categories?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  profile_picture?: T;
  position?: T;
  location?: T;
  social_body?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  video_featured?: T;
  video_rgpd_confirmation?: T;
  video_file_length?: T;
  video_file?: T;
  video_declaration_signed?: T;
  video_authors?: T;
  video_section?: T;
  video_introduction?: T;
  video_description?: T;
  author?: T;
  slug?: T;
  categories?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prizes_select".
 */
export interface PrizesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo?: (string | null) | Media;
  academiaDropdownLogo?: (string | null) | Media;
  navigationItems?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  academyDropdownMenu?:
    | {
        label: string;
        url: string;
        logo?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo?: (string | null) | Media;
  navigation_items?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newVideoPage".
 */
export interface NewVideoPage {
  id: string;
  image?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account".
 */
export interface Account {
  id: string;
  logo?: (string | null) | Media;
  logo_logged?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videosPage".
 */
export interface VideosPage {
  id: string;
  image: string | Media;
  logo_right: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  academiaDropdownLogo?: T;
  navigationItems?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  academyDropdownMenu?:
    | T
    | {
        label?: T;
        url?: T;
        logo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  navigation_items?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newVideoPage_select".
 */
export interface NewVideoPageSelect<T extends boolean = true> {
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account_select".
 */
export interface AccountSelect<T extends boolean = true> {
  logo?: T;
  logo_logged?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videosPage_select".
 */
export interface VideosPageSelect<T extends boolean = true> {
  image?: T;
  logo_right?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}