/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    paginas: Pagina;
    events: Event;
    users: User;
    media: Media;
    categories: Category;
    consensos: Consenso;
    noticias: Noticia;
    publications: Publication;
    courses: Course;
    sections: Section;
    nucleos: Nucleo;
    members: Member;
    videos: Video;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: string;
  titulo?: string | null;
  slug?: string | null;
  layout?: unknown[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  is_featured?: boolean | null;
  event_type: 'spg' | 'patrocinado' | 'outros';
  start_date: string;
  end_date: string;
  links_group?: {
    link_to_official_page?: string | null;
    link_to_facebook?: string | null;
    link_to_register?: string | null;
    link_to_program?: string | null;
  };
  sections?:
    | {
        title: string;
        evento_section_type?: ('texto' | 'Fotografias' | 'Vídeo') | null;
        content?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        images?:
          | {
              image: string | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        video?: string | null;
        id?: string | null;
      }[]
    | null;
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  description?: string | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consensos".
 */
export interface Consenso {
  id: string;
  title: string;
  consenso_type: 'file' | 'url';
  consenso_file?: (string | null) | Media;
  consenso_url?: string | null;
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: string;
  title: string;
  is_featured?: boolean | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: string;
  title: string;
  publication_file: string | Media;
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: string;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: string;
  title: string;
  mission: string;
  first_column: {
    title: string;
    message: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  second_column: {
    title: string;
    message: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  members?:
    | {
        picture?: (string | null) | Media;
        name: string;
        position?: string | null;
        location?: string | null;
        id?: string | null;
      }[]
    | null;
  useful_links?:
    | {
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  buttons?:
    | {
        title: string;
        type?: ('url' | 'file') | null;
        url?: string | null;
        file?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  recomended_articles?:
    | {
        title: string;
        type?: ('url' | 'file') | null;
        url?: string | null;
        file?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  workshops?:
    | {
        title: string;
        type?: ('url' | 'file') | null;
        url?: string | null;
        file?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  contacts?:
    | {
        type?: ('email' | 'phone') | null;
        email?: string | null;
        phone?: string | null;
        id?: string | null;
      }[]
    | null;
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nucleos".
 */
export interface Nucleo {
  id: string;
  title: string;
  mission: string;
  first_column: {
    title: string;
    message: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  second_column: {
    title: string;
    message: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  members?:
    | {
        picture?: (string | null) | Media;
        name: string;
        position?: string | null;
        location?: string | null;
        id?: string | null;
      }[]
    | null;
  useful_links?:
    | {
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  buttons?:
    | {
        title: string;
        type?: ('url' | 'file') | null;
        url?: string | null;
        file?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  recomended_articles?:
    | {
        title: string;
        type?: ('url' | 'file') | null;
        url?: string | null;
        file?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  workshops?:
    | {
        title: string;
        type?: ('url' | 'file') | null;
        url?: string | null;
        file?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  contacts?:
    | {
        type?: ('email' | 'phone') | null;
        email?: string | null;
        phone?: string | null;
        id?: string | null;
      }[]
    | null;
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: string;
  name: string;
  profile_picture: string | Media;
  position?: string | null;
  location?: string | null;
  social_body?: ('direcao' | 'assembleia-geral' | 'conselho-fiscal' | 'conselho-consultivo') | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: string;
  title: string;
  video_featured?: boolean | null;
  video_rgpd_confirmation: boolean;
  video_file_length?: string | null;
  video_file: string | Media;
  video_declaration_signed?: (string | null) | Media;
  video_authors: string;
  video_section:
    | 'geral'
    | 'colposcopia_patologia_tracto_genital_inferior'
    | 'endoscopia_ginecologica'
    | 'ginecologia_oncologica'
    | 'menopausa'
    | 'uroginecologia';
  video_introduction: string;
  video_description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author: string | User;
  slug?: string | null;
  categories?: (string | Category)[] | null;
  featured?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'paginas';
        value: string | Pagina;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'consensos';
        value: string | Consenso;
      } | null)
    | ({
        relationTo: 'noticias';
        value: string | Noticia;
      } | null)
    | ({
        relationTo: 'publications';
        value: string | Publication;
      } | null)
    | ({
        relationTo: 'courses';
        value: string | Course;
      } | null)
    | ({
        relationTo: 'sections';
        value: string | Section;
      } | null)
    | ({
        relationTo: 'nucleos';
        value: string | Nucleo;
      } | null)
    | ({
        relationTo: 'members';
        value: string | Member;
      } | null)
    | ({
        relationTo: 'videos';
        value: string | Video;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo?: (string | null) | Media;
  navigation_items?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo?: (string | null) | Media;
  navigation_items?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}