/* * */

export const UserDefault = {
	address_1: '',
	address_2: '',
	billing_address_1: '',
	billing_address_2: '',
	billing_city: '',
	billing_name: '',
	billing_postal_code: '',
	billing_tax_id: '',
	birthday: null,
	city: '',
	country: 'Portugal',
	email: '',
	full_name: '',
	last_name: '',
	name: '',
	phone: '',
	postal_code: '',
	send_newsletter: true,
	send_notifications: true,
	subscribed_sections: [],
	title: null,
	workplace_primary: '',
	workplace_secondary: '',
};
